### ISSUE TITLE
Does any one check the issues??

### ISSUE THREAD

**Issue by fabltd** [arduino/ArduinoCloudProviderExamples#14]
No response to any issue for 4 months?

**Comment by netskink** [comment]
Do you have a particular issue you are interested in?  I will help if I can.

**Comment by per1234** [comment]
Hi @fabltd. You are correct that this repository has been poorly maintained. I do apologize for that, but this isn't the type of thing that an issue tracker is well suited for tracking so I will close this for the sake of keeping the issue tracker tidy.

The specific open issues serve to track the need for maintainers and developers to take action.
