### ISSUE TITLE
AWS iot is unable to connect with GSM 900 module

### ISSUE THREAD

**Issue by PRADIPMAHAJAN** [arduino/ArduinoCloudProviderExamples#16]
Hello, I am trying to connect aws IOT with the GSM900 module using the cellular network. But I have no idea how I can connect with the aws iot thing. I did this by the wifi its worked successfully but it's not working with the GSM SIM900 module. please help me.

**Comment by per1234** [comment]
Hi @PRADIPMAHAJAN. Thanks for taking the time to submit an issue. The GSM examples we provide are specifically for use with the [**MKR GSM 1400**](https://docs.arduino.cc/hardware/mkr-gsm-1400) board.  It is expected that the examples will not work with the SIM900 module.

As for adding coverage for the SIM900 module, that is out of scope for this project.
