### ISSUE TITLE
Google Cloud IOT Core Fails to connect

### ISSUE THREAD

**Issue by fabltd** [arduino/ArduinoCloudProviderExamples#9]
Hi 

Have followed this example:

https://create.arduino.cc/projecthub/Arduino_Genuino/securely-connecting-a-mkr-gsm-1400-to-google-cloud-iot-core-b8b628

But it just keeps waiting at: Attempting to connect to MQTT Broker.

JT

**Comment by zjbarg** [comment]
Solved?

**Comment by fabltd** [comment]
Was.

The problem has happened again. Refuses to connect. Its been working fine and on the 9th of June it stopped and no more. Not sure what changed.

**Comment by adham995** [comment]
same problem.

Not sure what changed ??

**Comment by adham995** [comment]
@fabltd 
today the problem has solved and all it's okay.
Not sure what changed in GCP.

**Comment by netskink** [comment]
Hmm. Its working for you now?

**Comment by adham995** [comment]
> Hmm. Its working for you now?

The problem again ???
Today not working ....

I think the problem from google cloud platform!!!

**Comment by netskink** [comment]
@adham995 are you having problems now?

**Comment by adham995** [comment]
> @adham995 are you having problems now?

Yes!!

**Comment by netskink** [comment]
Hmm, but it worked before? Have you seen my work here? https://github.com/netskink/ssl_publy

**Comment by adham995** [comment]
> Hmm, but it worked before? Have you seen my work here? https://github.com/netskink/ssl_publy

Yes, it worked before.
It works for long time and some days not working, so the problem not related with software/programming the problem from cloud platform.

**Comment by netskink** [comment]
Hmm.  I have yet to get it working.  I stopped work on the project but my pal said he got it working using the GCP sample.  Rather than work on the problem directly, I have been learning SSL/TLS and certificates.  If I get a solution, I'll post it.  Please keep me posted.

**Comment by netskink** [comment]
I got this working.  My method was shown on the github repo I provided above.

**Comment by adham995** [comment]
> I got this working.  My method was shown on the github repo I provided above.

I will use your method. Any way I'm using the HTTP protocol and it works with out interruption.

**Comment by netskink** [comment]
Very good.  I have a discussion section open on my repo.  Feel free to ask questions there.  I plan to edit that repo for clarity.

**Comment by per1234** [comment]
Thanks for your report @fabltd 
> the problem not related with software/programming the problem from cloud platform.

Since you have determined that the fault is not caused by the code hosted in this repository, I will close this as off topic.
